# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16 ]

    name: Node v${{ matrix.node }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Install Sample
      run: |
        npm run install:local
        npm install
    - name: E2E Tests
      timeout-minutes: 10
      env:
        AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
        AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}
        AAD_TEST_USER_USERNAME: ${{ secrets.AAD_TEST_USER_USERNAME }}
        AAD_TEST_USER_PASSWORD: ${{ secrets.AAD_TEST_USER_PASSWORD }}
      run: npm test

    - name: Upload E2E Test Screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: e2e-test-screenshots
        path: demo/test/screenshots
